### ISSUE TITLE
Fail with obscure message when branch named `release-please` already exists

### ISSUE THREAD

**Issue by dyladan** [googleapis/release-please#1024]
I discovered the issue, and it is that I had a branch named `release-please`. When the automation tried to create the branch `release-please/branches/<branch-name>`, it failed with an opaque error message which didn't make it at all obvious what had happened.

I would suggest checking for an existing branch with that name before trying to create the ref, or adding to the error message that this might happen if a branch with the name `release-please` already exists.

### Original Issue Below

When trying to run release-please either from the command line or as a github action, it is failing with "Reference update failed" on `POST https://api.github.com/repos/dyladan/opentelemetry-js/git/refs`

Here is the command I ran:

```sh
release-please manifest-pr --token=<token> --default-branch=release-please-test --repo-url=https://github.com/dyladan/opentelemetry-js.git
```

Here is the failing request as it is printed in the debug output:

```
✔ Retry attempt #2...
✔ Successfully found branch HEAD sha "a32cfa70f5b42d7c80025da0410c8c90ecd0fbae".
✖ Error when creating branch
✖ RequestError [HttpError]: Error creating Pull Request: Reference update failed
    at /Users/daniel.dyla/.nvm/versions/node/v14.8.0/lib/node_modules/release-please/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createBranch (/Users/daniel.dyla/.nvm/versions/node/v14.8.0/lib/node_modules/release-please/node_modules/code-suggester/build/src/github/branch.js:81:26)
    at async Object.branch (/Users/daniel.dyla/.nvm/versions/node/v14.8.0/lib/node_modules/release-please/node_modules/code-suggester/build/src/github/branch.js:109:9)
    at async retry.retries (/Users/daniel.dyla/.nvm/versions/node/v14.8.0/lib/node_modules/release-please/node_modules/code-suggester/build/src/index.js:105:48)
    at async Object.createPullRequest (/Users/daniel.dyla/.nvm/versions/node/v14.8.0/lib/node_modules/release-please/node_modules/code-suggester/build/src/index.js:105:24)
    at async /Users/daniel.dyla/.nvm/versions/node/v14.8.0/lib/node_modules/release-please/build/src/github.js:285:30
    at async GitHub.openPR (/Users/daniel.dyla/.nvm/versions/node/v14.8.0/lib/node_modules/release-please/build/src/github.js:1391:20)
    at async Manifest.pullRequest (/Users/daniel.dyla/.nvm/versions/node/v14.8.0/lib/node_modules/release-please/build/src/manifest.js:423:20) {
  status: 422,
  response: {
    url: 'https://api.github.com/repos/dyladan/opentelemetry-js/git/refs',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
      connection: 'close',
      'content-length': '121',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 26 Aug 2021 19:05:49 GMT',
      'github-authentication-token-expiration': '2021-09-25 18:54:47 UTC',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'D886:40F4:28CC7A:525E6E:6127E60D',
      'x-oauth-scopes': 'repo',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '3793',
      'x-ratelimit-reset': '1630006619',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1207',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Reference update failed',
      documentation_url: 'https://docs.github.com/rest/reference/git#create-a-reference'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/dyladan/opentelemetry-js/git/refs',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.9.1 octokit-core.js/3.5.1 Node.js/14.8.0 (darwin; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"ref":"refs/heads/release-please/branches/release-please-test","sha":"a32cfa70f5b42d7c80025da0410c8c90ecd0fbae"}',
    request: { hook: [Function: bound bound register] }
  }
}
```
 
#### Environment details

  - OS: Linux and MacOS
  - Node.js version: 14 and 16
  - npm version: 6 and 7
  - `release-please` version: 11.22.0

#### Steps to reproduce

I'm not sure if it is reproducible, but you can see the result here: https://github.com/dyladan/opentelemetry-js/actions/runs/1171694993

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment]
We should consider changing the branch name delimiter to avoid this restriction from git and to keep the branch names easily parseable.
