### ISSUE TITLE
Getting ETIMEDOUT during large iterations

### ISSUE THREAD

**Issue by dazuma** [googleapis/release-please#1379]
The google-cloud-ruby monorepo is very large, with ~300 packages (and growing), each with its own set of releases/tags/etc. The PR count just recently broke 18000 and the rate is likely to accelerate.

release-please has several processes that involve iterating over repo objects such as tags, releases, PRs, commits, etc. When these iterations are not capped (or have a large cap), they sometimes fail with timeouts. It feels almost like the iteration is hitting the API too rapidly and gets throttled suddenly. It ends up looking like this:

```
RequestError [HttpError]: request to https://api.github.com/repositories/20343475/tags?page=38 failed, reason: connect ETIMEDOUT 192.30.255.116:443
    at /usr/local/google/home/dazuma/src/github/release-please/node_modules/@octokit/request/dist-node/index.js:108:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.next (/usr/local/google/home/dazuma/src/github/release-please/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:124:28)
    at async GitHub.tagIterator (/usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:789:26)
    at async Manifest.getAllTags (/usr/local/google/home/dazuma/src/github/release-please/build/src/manifest.js:386:26)
    at async Manifest.backfillReleasesFromTags (/usr/local/google/home/dazuma/src/github/release-please/build/src/manifest.js:361:25)
    at async Manifest.buildPullRequests (/usr/local/google/home/dazuma/src/github/release-please/build/src/manifest.js:212:37)
    at async Object.handler (/usr/local/google/home/dazuma/src/github/release-please/build/src/bin/release-please.js:296:34) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repositories/20343475/tags?page=38',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.6.0 Node.js/16.13.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

Is there a way we can retry API requests that are made during iteration, with a suitable fairly long backoff to deal with throttling?

**Comment by dazuma** [comment]
Still seeing these with 13.10.1. Latest example, while iterating through "Fetching CLOSED pull requests on branch main with cursor..."

```
HttpError: request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 192.30.255.116:443
    at /usr/local/google/home/dazuma/src/github/release-please/node_modules/@octokit/request/dist-node/index.js:108:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:65:38
    at async GitHub.graphqlRequest (/usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:981:20)
    at async GitHub.pullRequestsGraphQL (/usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:640:26)
    at async GitHub.pullRequestIterator (/usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:611:30)
    at async Manifest.findSnoozedReleasePullRequests (/usr/local/google/home/dazuma/src/github/release-please/build/src/manifest.js:438:26)
    at async Manifest.createPullRequests (/usr/local/google/home/dazuma/src/github/release-please/build/src/manifest.js:410:37)
    at async Object.handler (/usr/local/google/home/dazuma/src/github/release-please/build/src/bin/release-please.js:313:40) {
  status: 500,
  body: undefined,
  name: 'GitHubAPIError',
  cause: RequestError [HttpError]: request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 192.30.255.116:443
      at /usr/local/google/home/dazuma/src/github/release-please/node_modules/@octokit/request/dist-node/index.js:108:11
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:65:38
      at async GitHub.graphqlRequest (/usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:981:20)
      at async GitHub.pullRequestsGraphQL (/usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:640:26)
      at async GitHub.pullRequestIterator (/usr/local/google/home/dazuma/src/github/release-please/build/src/github.js:611:30)
      at async Manifest.findSnoozedReleasePullRequests (/usr/local/google/home/dazuma/src/github/release-please/build/src/manifest.js:438:26)
      at async Manifest.createPullRequests (/usr/local/google/home/dazuma/src/github/release-please/build/src/manifest.js:410:37)
      at async Object.handler (/usr/local/google/home/dazuma/src/github/release-please/build/src/bin/release-please.js:313:40) {
    status: 500,
    request: {
      method: 'POST',
      url: 'https://api.github.com/graphql',
      headers: [Object],
      body: '{"query":"query mergedPullRequests($owner: String!, $repo: String!, $num: Int!, $maxFilesChanged: Int, $targetBranch: String!, $states: [PullRequestState!], $cursor: String) {\\n        repository(owner: $owner, name: $repo) {\\n          pullRequests(first: $num, after: $cursor, baseRefName: $targetBranch, states: $states, orderBy: {field: CREATED_AT, direction: DESC}) {\\n            nodes {\\n              number\\n              title\\n              baseRefName\\n              headRefName\\n              labels(first: 10) {\\n                nodes {\\n                  name\\n                }\\n              }\\n              body\\n              mergeCommit {\\n                oid\\n              }\\n              files(first: $maxFilesChanged) {\\n                nodes {\\n                  path\\n                }\\n                pageInfo {\\n                  endCursor\\n                  hasNextPage\\n                }\\n              }\\n            }\\n            pageInfo {\\n              endCursor\\n              hasNextPage\\n            }\\n          }\\n        }\\n      }","variables":{"cursor":"Y3Vyc29yOnYyOpK5MjAyMi0wMS0wNFQyMTo0ODozNy0wODowMM4wivRY","owner":"googleapis","repo":"google-cloud-ruby","num":25,"targetBranch":"main","states":"CLOSED","maxFilesChanged":64}}'
    }
  }
}
```

**Comment by chingor13** [comment]
After some investigate, it looks like this is an environment networking issue where the requests are being throttled.
