### ISSUE TITLE
Invalid previous_tag parameter

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/release-please#1787]
Found in logs:
```
{
  "insertId": "6397541c000bb765b0bcf1d6",
        "status": 400,
        "data": {
          "documentation_url": "https://docs.github.com/rest/reference/repos#generate-release-notes",
          "message": "Invalid previous_tag parameter"
        },
        "url": "https://api.github.com/repos/tetra-insights/next-refarch/releases/generate-notes"
      },
      "stack": "HttpError: Invalid previous_tag parameter\n    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:376:12)\n    at async GitHub.generateReleaseNotes (/usr/src/app/node_modules/release-please/build/src/github.js:1075:22)\n    at async GitHubChangelogNotes.buildNotes (/usr/src/app/node_modules/release-please/build/src/changelog-notes/github.js:22:16)\n    at async KRMBlueprint.buildReleaseNotes (/usr/src/app/node_modules/release-please/build/src/strategies/base.js:109:16)\n    at async KRMBlueprint.buildReleasePullRequest (/usr/src/app/node_modules/release-please/build/src/strategies/base.js:159:34)\n    at async Manifest.buildPullRequests (/usr/src/app/node_modules/release-please/build/src/manifest.js:346:40)\n    at async Manifest.createPullRequests (/usr/src/app/node_modules/release-please/build/src/manifest.js:418:39)",
      "message": "Invalid previous_tag parameter",
      "status": 400,
}
```

It happened 13 times in 27 minutes on December 12th, and hasn't happened since.

**Comment by lacolaco** [comment]
I've seen the same error message recently. In my situation, it solved by removing `changelog-type` configuration and using the default format.

**Comment by nick-marnik** [comment]
Adding my 2 cents - I think this may be a bug. Temporarily switching the `changelog-type` to `default` fixes the error for the initial run of release-please. And switching to `github` immediately after still works, too.
