### ISSUE TITLE
Test suite fails on Node 18

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1803]
The test suite fails on Node 18 with many failures related to errors:

```
  19) GitHub
       getFileContents
         should support Github Data API in case of a big file:
     FileNotFoundError: Failed to find file: package-lock.json
      at GitHub.getFileContentsOnBranch (src/github.ts:954:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at GitHub.getFileContents (src/github.ts:930:12)
      at Context.<anonymous> (test/github.ts:259:28)

  20) GitHub
       pullRequestIterator
         finds merged pull requests with labels:
     HttpError: Bad credentials
      at <anonymous> (node_modules/@octokit/request/dist-src/fetch-wrapper.js:70:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at <anonymous> (src/github.ts:570:28)
      at GitHub.graphqlRequest (src/github.ts:1674:14)
      at GitHub.pullRequestsGraphQL (src/github.ts:734:22)
      at GitHub.pullRequestIteratorWithFiles (src/github.ts:642:9)
      at GitHub.pullRequestIterator (src/github.ts:620:22)
      at Context.<anonymous> (test/github.ts:286:24)

  21) GitHub
       pullRequestIterator
         handles merged pull requests without files:
     HttpError: Bad credentials
      at <anonymous> (node_modules/@octokit/request/dist-src/fetch-wrapper.js:70:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at <anonymous> (src/github.ts:570:28)
      at GitHub.graphqlRequest (src/github.ts:1674:14)
      at GitHub.pullRequestsGraphQL (src/github.ts:734:22)
      at GitHub.pullRequestIteratorWithFiles (src/github.ts:642:9)
      at GitHub.pullRequestIterator (src/github.ts:620:22)
      at Context.<anonymous> (test/github.ts:305:24)
```

This may be good to investigate, since it could be affecting users running Node 18.

**Comment by SurferJeffAtGoogle** [comment]
I don't see this test failing anymore.  I see another, for which I'll open a new issue.

**Comment by mrienstra** [comment]
@SurferJeffAtGoogle, how did you resolve this? I have 48 tests failing (819 passing), many seem to have errors similar to yours, e.g. `HttpError: Bad credentials` was the error for 14 failing tests.

I also have `HttpError: Not Found` 28 times, plus one occurrence of `GitHubAPIError: Not Found` (which I believe is the same underlying error) and one occurrence of `GitHubAPIError: Bad credentials` (which I believe is the same underlying error as `HttpError: Bad credentials`, so overall I'm guessing 44/48 are all problems with the GitHub API.

I'm using Node v19.6.0. Here's a gist showing the output of `npm test`: https://gist.github.com/mrienstra/518f14a32887bc591cf838a52d46879b

Not seeing any errors when running `npm install`.

**Comment by mchenryc** [comment]
This is due to a change in how network calls are made in NodeJS 18, which are not (yet) supported by Nock:

From  https://github.com/nock/nock/issues/2183
> NodeJS has a new vertical http client named [undici](https://github.com/nodejs/undici) which is much more performant.
> Nock does not mock responses for undici users.

Discussion on 2183 includes a few options:
1. use undici's mocking library instead of nock
2. disable fetch w/ `--no-experimental-fetch` and include a polyfill
3. wait for nock to incorporate undici

Running tests still works under node 17
