### ISSUE TITLE
Error adding to tree: 496f93556d711f1e569ea7e6d9e27aee77a8bb6d

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/release-please#1898]
Seen once in logs:
```
{
  "insertId": "642489620003763cc7ffc6a7",
  "jsonPayload": {
    "level": 50,
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
    "trigger": {
      "trigger_source_repo": {
        "owner_type": "Organization",
        "repo_name": "ibis-bigquery",
        "owner": "ibis-project",
        "url": "https://github.com/ibis-project/ibis-bigquery"
      },
      "trigger_sender": "tswast",
      "github_event_type": "push",
      "payload_hash": "de289fe60de39eb0102f593cd92439fb",
      "github_delivery_guid": "c93416aa-ce56-11ed-84cb-8441c0d538a2",
      "trigger_type": "Cloud Task"
    },
    "err": {
      "message": "Error adding to tree: 496f93556d711f1e569ea7e6d9e27aee77a8bb6d: Resource not accessible by integration",
      "type": "CommitError",
      "event": {
        "name": "push",
        "id": "c93416aa-ce56-11ed-84cb-8441c0d538a2",
        "payload": {
          "repository": {
            "has_issues": true,
            "comments_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/comments{/number}",
            "disabled": false,
            "size": 176,
            "issue_events_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/issues/events{/number}",
            "open_issues_count": 44,
            "milestones_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/milestones{/number}",
            "has_downloads": true,
            "stargazers_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/stargazers",
            "hooks_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/hooks",
            "compare_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/compare/{base}...{head}",
            "watchers_count": 18,
            "organization": "ibis-project",
            "issues_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/issues{/number}",
            "stargazers": 18,
            "pulls_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/pulls{/number}",
            "commits_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/commits{/sha}",
            "svn_url": "https://github.com/ibis-project/ibis-bigquery",
            "open_issues": 44,
            "contents_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/contents/{+path}",
            "visibility": "public",
            "trees_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/git/trees{/sha}",
            "blobs_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/git/blobs{/sha}",
            "fork": false,
            "created_at": 1617904193,
            "forks_count": 19,
            "owner": {
              "site_admin": false,
              "gists_url": "https://api.github.com/users/ibis-project/gists{/gist_id}",
              "events_url": "https://api.github.com/users/ibis-project/events{/privacy}",
              "email": null,
              "node_id": "MDEyOk9yZ2FuaXphdGlvbjI3NDQyNTI2",
              "followers_url": "https://api.github.com/users/ibis-project/followers",
              "following_url": "https://api.github.com/users/ibis-project/following{/other_user}",
              "html_url": "https://github.com/ibis-project",
              "type": "Organization",
              "starred_url": "https://api.github.com/users/ibis-project/starred{/owner}{/repo}",
              "organizations_url": "https://api.github.com/users/ibis-project/orgs",
              "login": "ibis-project",
              "id": 27442526,
              "gravatar_id": "",
              "name": "ibis-project",
              "url": "https://api.github.com/users/ibis-project",
              "repos_url": "https://api.github.com/users/ibis-project/repos",
              "avatar_url": "https://avatars.githubusercontent.com/u/27442526?v=4",
              "received_events_url": "https://api.github.com/users/ibis-project/received_events",
              "subscriptions_url": "https://api.github.com/users/ibis-project/subscriptions"
            },
            "languages_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/languages",
            "teams_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/teams",
            "stargazers_count": 18,
            "language": "Python",
            "labels_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/labels{/name}",
            "git_tags_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/git/tags{/sha}",
            "events_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/events",
            "id": 356001118,
            "html_url": "https://github.com/ibis-project/ibis-bigquery",
            "full_name": "ibis-project/ibis-bigquery",
            "archived": false,
            "collaborators_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/collaborators{/collaborator}",
            "forks_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/forks",
            "default_branch": "main",
            "has_pages": false,
            "has_discussions": false,
            "mirror_url": null,
            "private": false,
            "allow_forking": true,
            "name": "ibis-bigquery",
            "homepage": null,
            "web_commit_signoff_required": false,
            "issue_comment_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/issues/comments{/number}",
            "merges_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/merges",
            "assignees_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/assignees{/user}",
            "watchers": 18,
            "has_wiki": true,
            "tags_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/tags",
            "statuses_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/statuses/{sha}",
            "description": "BigQuery backend for Ibis",
            "updated_at": "2022-12-07T21:17:37Z",
            "topics": [],
            "clone_url": "https://github.com/ibis-project/ibis-bigquery.git",
            "subscribers_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/subscribers",
            "notifications_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/notifications{?since,all,participating}",
            "is_template": false,
            "contributors_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/contributors",
            "archive_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/{archive_format}{/ref}",
            "url": "https://github.com/ibis-project/ibis-bigquery",
            "downloads_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/downloads",
            "deployments_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/deployments",
            "branches_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/branches{/branch}",
            "releases_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/releases{/id}",
            "license": {
              "url": "https://api.github.com/licenses/apache-2.0",
              "name": "Apache License 2.0",
              "key": "apache-2.0",
              "node_id": "MDc6TGljZW5zZTI=",
              "spdx_id": "Apache-2.0"
            },
            "keys_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/keys{/key_id}",
            "master_branch": "main",
            "has_projects": true,
            "forks": 19,
            "git_url": "git://github.com/ibis-project/ibis-bigquery.git",
            "pushed_at": 1680110763,
            "git_refs_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/git/refs{/sha}",
            "subscription_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/subscription",
            "ssh_url": "git@github.com:ibis-project/ibis-bigquery.git",
            "git_commits_url": "https://api.github.com/repos/ibis-project/ibis-bigquery/git/commits{/sha}",
            "node_id": "MDEwOlJlcG9zaXRvcnkzNTYwMDExMTg="
          },
          "forced": false,
          "base_ref": null,
          "organization": {
            "events_url": "https://api.github.com/orgs/ibis-project/events",
            "hooks_url": "https://api.github.com/orgs/ibis-project/hooks",
            "url": "https://api.github.com/orgs/ibis-project",
            "public_members_url": "https://api.github.com/orgs/ibis-project/public_members{/member}",
            "issues_url": "https://api.github.com/orgs/ibis-project/issues",
            "id": 27442526,
            "repos_url": "https://api.github.com/orgs/ibis-project/repos",
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjI3NDQyNTI2",
            "members_url": "https://api.github.com/orgs/ibis-project/members{/member}",
            "login": "ibis-project",
            "description": "Expressive analytics at any scale.",
            "avatar_url": "https://avatars.githubusercontent.com/u/27442526?v=4"
          },
          "sender": {
            "node_id": "MDQ6VXNlcjI0NzU1NQ==",
            "url": "https://api.github.com/users/tswast",
            "received_events_url": "https://api.github.com/users/tswast/received_events",
            "subscriptions_url": "https://api.github.com/users/tswast/subscriptions",
            "type": "User",
            "avatar_url": "https://avatars.githubusercontent.com/u/247555?v=4",
            "starred_url": "https://api.github.com/users/tswast/starred{/owner}{/repo}",
            "gravatar_id": "",
            "following_url": "https://api.github.com/users/tswast/following{/other_user}",
            "site_admin": false,
            "followers_url": "https://api.github.com/users/tswast/followers",
            "events_url": "https://api.github.com/users/tswast/events{/privacy}",
            "gists_url": "https://api.github.com/users/tswast/gists{/gist_id}",
            "repos_url": "https://api.github.com/users/tswast/repos",
            "id": 247555,
            "html_url": "https://github.com/tswast",
            "login": "tswast",
            "organizations_url": "https://api.github.com/users/tswast/orgs"
          },
          "commits": [
            {
              "committer": {
                "name": "GitHub",
                "email": "noreply@github.com",
                "username": "web-flow"
              },
              "id": "496f93556d711f1e569ea7e6d9e27aee77a8bb6d",
              "modified": [
                "README.rst"
              ],
              "timestamp": "2023-03-29T12:26:03-05:00",
              "url": "https://github.com/ibis-project/ibis-bigquery/commit/496f93556d711f1e569ea7e6d9e27aee77a8bb6d",
              "removed": [],
              "added": [],
              "author": {
                "username": "gforsyth",
                "name": "Gil Forsyth",
                "email": "gforsyth@users.noreply.github.com"
              },
              "distinct": true,
              "tree_id": "d0daf5a3abc88eab68aac94260e91184f2e35ae4",
              "message": "docs(README): make note that the bigquery backend is now upstream (#155)"
            }
          ],
          "created": false,
          "ref": "refs/heads/main",
          "head_commit": {
            "removed": [],
            "distinct": true,
            "tree_id": "d0daf5a3abc88eab68aac94260e91184f2e35ae4",
            "url": "https://github.com/ibis-project/ibis-bigquery/commit/496f93556d711f1e569ea7e6d9e27aee77a8bb6d",
            "id": "496f93556d711f1e569ea7e6d9e27aee77a8bb6d",
            "author": {
              "email": "gforsyth@users.noreply.github.com",
              "username": "gforsyth",
              "name": "Gil Forsyth"
            },
            "added": [],
            "message": "docs(README): make note that the bigquery backend is now upstream (#155)",
            "modified": [
              "README.rst"
            ],
            "timestamp": "2023-03-29T12:26:03-05:00",
            "committer": {
              "email": "noreply@github.com",
              "username": "web-flow",
              "name": "GitHub"
            }
          },
          "pusher": {
            "email": "swast@google.com",
            "name": "tswast"
          },
          "after": "496f93556d711f1e569ea7e6d9e27aee77a8bb6d",
          "deleted": false,
          "compare": "https://github.com/ibis-project/ibis-bigquery/compare/256f5df3d38a...496f93556d71",
          "before": "256f5df3d38a5519cd7154271fd1d71416755c51",
          "installation": {
            "id": 16564098,
            "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTY1NjQwOTg="
          }
        }
      },
      "stack": "Error: Error adding to tree: 496f93556d711f1e569ea7e6d9e27aee77a8bb6d\n    at createTree (/usr/src/app/node_modules/code-suggester/build/src/github/commit-and-push.js:87:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async commitAndPush (/usr/src/app/node_modules/code-suggester/build/src/github/commit-and-push.js:133:25)\n    at async createPullRequest (/usr/src/app/node_modules/code-suggester/build/src/index.js:140:5)\n    at async /usr/src/app/node_modules/release-please/build/src/github.js:146:30\n    at async GitHub.createPullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1222:20)\n    at async Manifest.createOrUpdatePullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:507:32)\n    at async Promise.all (index 0)\n    at async Manifest.createPullRequests (/usr/src/app/node_modules/release-please/build/src/manifest.js:447:33)\ncaused by: HttpError: Resource not accessible by integration\n    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async sendRequestWithRetries (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:349:12)\n    at async createTree (/usr/src/app/node_modules/code-suggester/build/src/github/commit-and-push.js:77:26)\n    at async commitAndPush (/usr/src/app/node_modules/code-suggester/build/src/github/commit-and-push.js:133:25)\n    at async createPullRequest (/usr/src/app/node_modules/code-suggester/build/src/index.js:140:5)\n    at async /usr/src/app/node_modules/release-please/build/src/github.js:146:30\n    at async GitHub.createPullRequest (/usr/src/app/node_modules/release-please/build/src/github.js:1222:20)\n    at async Manifest.createOrUpdatePullRequest (/usr/src/app/node_modules/release-please/build/src/manifest.js:507:32)"
    },
    "message": "Error adding to tree: 496f93556d711f1e569ea7e6d9e27aee77a8bb6d"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "service_name": "release-please-backend",
      "configuration_name": "release-please-backend",
      "project_id": "repo-automation-bots",
      "location": "us-central1",
      "revision_name": "release-please-backend-00047-naq"
    }
  },
  "timestamp": "2023-03-29T18:54:26.226876Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00121789b37470a691009e322c9e75a23848f3993ebc4e1306091a0846afbab425ed435b043789cd0dbc64e33197bb36fd39133061d9fbfb89ffd5ffe7ee596fe6"
  },
  "logName": "projects/repo-automation-bots/logs/run.googleapis.com%2Fstdout",
  "trace": "projects/repo-automation-bots/traces/4156bcfd64c9b4a23bf2e527a351b805",
  "receiveTimestamp": "2023-03-29T18:54:26.558666160Z"
}
```

**Comment by chingor13** [comment]
This is thrown from the upstream [googleapis/code-suggester](https://github.com/googleapis/code-suggester) library. This is likely a race condition where 2 instances of release-please are trying to write commits to the same branch and one wins out.

**Comment by chingor13** [comment]
After further investigation, this happened a bunch of times in a row from the same webhook guid: `c93416aa-ce56-11ed-84cb-8441c0d538a2`. Looking further.

**Comment by chingor13** [comment]
Oh, the repo https://github.com/ibis-project/ibis-bigquery is archived so release-please app can't push commits
