### ISSUE TITLE
[node release-type] - TypeError: versionString.match is not a function - Trying to setup multiple packages in a monorepo with independent changelogs

### ISSUE THREAD

**Issue by jamesmortensen** [googleapis/release-please#1953]
I'm trying to setup a monorepo with a few independent packages so that I can generate changelogs for them independently of one another.  I followed instructions as best as possible to configure everything, but I'm not sure what I'm doing wrong.  When trying to run release-pr, I'm seeing the following error message:

```
TypeError: versionString.match is not a function
    at Version.parse (/Users/james/Dev/release-please-demo/node_modules/release-please/build/src/version.js:38:37)
    at parseReleasedVersions (/Users/james/Dev/release-please-demo/node_modules/release-please/build/src/manifest.js:870:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Manifest.fromManifest (/Users/james/Dev/release-please-demo/node_modules/release-please/build/src/manifest.js:121:93)
    at async Object.handler (/Users/james/Dev/release-please-demo/node_modules/release-please/build/src/bin/release-please.js:309:24)
```

#### Environment details

  - OS:
  - Node.js version:  18.3.0
  - npm version: 8.11.0
  - `release-please` version:  15.10.4

#### Steps to reproduce

  1.  Created a config file with the following information:

```
{
  "packages": {
    "packages/pkg1": {
    },
    "packages/pkg2": {
    }
  },
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}
```

Created a .release-please-manifest.json:

```
{
  "packages": {
    "packages/pkg1": "0.0.1",
    "packages/pkg2": "0.0.1"
  }
}
```

  3. Committed this to the main branch
  4. Create a new npm project in packages/pkg1 and packages/pkg2 with their own package.json

Then run the following command:

```
$ npx release-please release-pr --repo-url=jamesmortensen/release-please-demo --token=$GITHUB_TOKEN --package-name=pkg1 --dry-run --debug --release-as="0.0.1"
```

I've tried several variations of the configuration options from this [section in the documentation on manifests](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile) and they all complain about the version.  I'm not sure if this is a bug or if there's something I'm doing wrong.  

If anyone wants to check out the repository, it's just a demo where I'm trying to understand more about how this works to generate CHANGELOG.md files:  https://github.com/jamesmortensen/release-please-demo

You can also see the commit history to get an idea of the path I went down to encounter these errors.  Hope this helps debug the issue, and thank you for any support you can provide.

**Comment by jamesmortensen** [comment]
After digging into the `release-please/build/src/manifest.js` file, I discovered that I had incorrectly placed the entries for each package in a "packages" entry, so release-please was trying to parse a version from the packages folder instead of packages/pkg1 and packages/pkg2.  

I updated the .release-please-manifest.json as follows:

```
{
    "packages/pkg1": "0.0.1",
    "packages/pkg2": "0.0.1"
}
```

My dry run was a success, so I'll continue moving forward and document whatever happens here.

**Comment by jamesmortensen** [comment]
I'm still not able to figure out how to get setup with a monorepo with two node.js packages.  It seems to only want to generate changelogs for the root package.json, but I want to generate changelogs for the individual packages only.

Here is my current config file:

```
{
  "bootstrap-sha": "9689268cd1586f9b64c05e4d2672c11b5347a3f6",
  "packages": {
    "packages/pkg1": "0.0.1",
    "packages/pkg2": "0.0.1"
  },
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}
```

and here is the manifest:

```
{
    "packages/pkg1": "0.0.1",
    "packages/pkg2": "0.0.1"
}
```

Here are the steps I followed:
1.  Commit the above changes to the main branch.  The bootstrap-sha is the previous commit. I assumed this would tell release-please to not consider all my earlier failed attempts and start from ground zero. _Later, you'll see this did not happen_. 
2. Create a new branch:  `git checkout -b pkg1-only`
3. On the new branch, make a few changes to the packages/pkg1/index.js file.
4. Commit and push the changes with a conventional commit:  `git commit -am "fix: added a log statement" && git push origin pkg1-only`
5. Run the CLI tool to generate a release-pr:

```
$ npx release-please release-pr --repo-url=jamesmortensen/release-please-demo --release-type=node --token=$GITHUB_TOKEN
```

Logs:

```
(node:926) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
❯ Fetching package.json from branch main
✔ Looking for latest release on branch: main with prefix: release-please-demo
❯ Fetching merge commits on branch main with cursor: undefined
❯ Found latest release pull request: 9 version: 1.1.0
❯ Fetching releases with cursor undefined
⚠ Could not find releases.
❯ found 1 possible releases. [
  Version {
    major: 1,
    minor: 1,
    patch: 0,
    preRelease: undefined,
    build: undefined
  }
]
✔ Building pull requests
✔ Building strategies by path
❯ .: node
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
⚠ Could not find releases.
⚠ Expected 1 releases, only found 0
⚠ Missing 1 paths: .
❯ looking for tagName: v1.1.0
⚠ Expected 1 releases, only found 0
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(0) {}
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 85fad084ae4a036c3fd054b176887b21f0a37f53
❯ Found 2 files
❯ Backfilling file list for commit: ad0f5db0e7659d450ab0607f1ca3716f59b34266
❯ Found 4 files
❯ Backfilling file list for commit: 59deae4c82e8ef8ab4e57dada7ece8f2d23f94eb
❯ Found 1 files
❯ Backfilling file list for commit: aa36873d86263b2a5071c4de1d4dfe471f8f0a45
❯ Found 1 files
❯ Backfilling file list for commit: 6ea10ee8cfc25a7cb08eedccf0b21840fa30326b
❯ Found 1 files
❯ Backfilling file list for commit: c8c8db6e5a7e72af753d9466aadb57630c5e98c2
❯ Found 2 files
❯ Backfilling file list for commit: 6ec5581c8711d8b064a15b9fd946d5544fa5e4e0
❯ Found 1 files
❯ Backfilling file list for commit: 6ede5b79e4c24fa96e7167f9e95cffb69d376461
❯ Found 1 files
❯ Backfilling file list for commit: 6b68b9953146a922a066c466fdb0627e253abf88
❯ Found 1 files
❯ Backfilling file list for commit: 5b928c7568767e6c4a544eef6b2e1d41ba52e433
❯ Found 1 files
❯ Backfilling file list for commit: 76fe5370c10338e1b257e40983c472c31a366a45
❯ Found 1 files
❯ Backfilling file list for commit: 8244f0813333a6ad61acd50d31e356e3cff2b84f
❯ Found 0 files
❯ Backfilling file list for commit: c5afada77268e06c902593009be47ce5746d3759
❯ Found 1 files
❯ Backfilling file list for commit: 959a3bad4223f612dfa0d64bf6da9085856fba7c
❯ Found 1 files
❯ Backfilling file list for commit: 8f35ea102d336d17d78c55fb8c6b9ffdd4a83d74
❯ Found 1 files
❯ Backfilling file list for commit: 3aa1c1ff01ae1eee5dc76e2054ae67cd4e31a6d0
❯ Found 1 files
❯ Backfilling file list for commit: dcf90f4b37bf8ca0c5b1878067fd92e2cbbf6e16
❯ Found 1 files
❯ Backfilling file list for commit: c2bd2a70b505d671e52f345e81ed0ad91acc11fb
❯ Found 2 files
❯ Backfilling file list for commit: 5d3d9e5a60f09deb1cd677bbbb526f89e5815429
❯ Found 1 files
❯ Backfilling file list for commit: 70981216f617946b870344e69507f096bb7f4289
❯ Found 1 files
❯ Fetching merge commits on branch main with cursor: 85fad084ae4a036c3fd054b176887b21f0a37f53 24
❯ Backfilling file list for commit: 6759f6b8690e27447867fd646a355ce93b3d3bc0
❯ Found 2 files
❯ Backfilling file list for commit: 3d82a7974c912ebb1a65e1e9334a305eeeced817
❯ Found 2 files
❯ Backfilling file list for commit: 1d75f29fe2f05095159d75c5a8f1683834506409
❯ Found 2 files
❯ Backfilling file list for commit: e865650afb075fd55fd1bb7bb03df0f74618a063
❯ Found 1 files
❯ Backfilling file list for commit: c583c94666e17e1d4223ffcdc4b0127a7101e0cd
❯ Found 2 files
❯ Backfilling file list for commit: d5c9609bdbf89b99ff59e2db8998a1e5b2b0f70c
❯ Found 4 files
✔ Splitting 32 commits by path
✔ No latest release found for path: ., component: , but a previous version (1.1.0) was specified in the manifest.
✔ Building candidate release pull request for path: .
❯ type: node
❯ targetBranch: main
❯ commit could not be parsed: 9689268cd1586f9b64c05e4d2672c11b5347a3f6 Merge pull request #9 from jamesmortensen/release-please--branches--main--components--release-please-demo
❯ commit could not be parsed: aa36873d86263b2a5071c4de1d4dfe471f8f0a45 trying another idea for the manifest based on what I'm seeing when debugging manifest.js in the package
❯ commit could not be parsed: 6ec5581c8711d8b064a15b9fd946d5544fa5e4e0 fix paths in config file - cleanup
❯ commit could not be parsed: 6ede5b79e4c24fa96e7167f9e95cffb69d376461 fix paths in config file
❯ commit could not be parsed: 6b68b9953146a922a066c466fdb0627e253abf88 clean manifest of root dir by just having 0.0.1 version string
❯ commit could not be parsed: 5b928c7568767e6c4a544eef6b2e1d41ba52e433 clean manifest of root dir by removing release-type node
❯ commit could not be parsed: 76fe5370c10338e1b257e40983c472c31a366a45 clean manifest of root dir
❯ commit could not be parsed: 8244f0813333a6ad61acd50d31e356e3cff2b84f Merge branch 'main' of https://github.com/jamesmortensen/release-please-demo
❯ commit could not be parsed: c5afada77268e06c902593009be47ce5746d3759 update manifest
❯ commit could not be parsed: 853af4eb9297a264787c3c196a2c13867b15c414 Merge pull request #6 from jamesmortensen/pkg2changes
❯ commit could not be parsed: 959a3bad4223f612dfa0d64bf6da9085856fba7c Update .release-please-manifest.json
❯ commit could not be parsed: dcf90f4b37bf8ca0c5b1878067fd92e2cbbf6e16 Updating .release-please-manifest.json with packages details from https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile
❯ commit could not be parsed: 27522412e32037331edf037673e7a2d8fbc9a828 Merge pull request #5 from jamesmortensen/release-please/bootstrap/packages
❯ commit could not be parsed: 2f8f79cee324ec65fdde90ec962acd781b227f94 Merge pull request #3 from jamesmortensen/pkg1-create
❯ commit could not be parsed: 3d5f70cbe496a3a42d2ca15b618f731aa40143e5 Merge pull request #2 from jamesmortensen/release-please--branches--main--components--release-please-demo
❯ commit could not be parsed: 3d82a7974c912ebb1a65e1e9334a305eeeced817 Merge branch 'main' of https://github.com/jamesmortensen/release-please-demo
❯ commit could not be parsed: 19c5b4968648609d4a5c6e92bf7a50b2875d28da Merge pull request #1 from jamesmortensen/release-please/bootstrap/default
❯ commit could not be parsed: e865650afb075fd55fd1bb7bb03df0f74618a063 Update release-please-config.json
❯ commits: 14
⚠ No latest release pull request found.
✔ Considering: 14 commits
❯ component: 
❯ pull request title pattern: undefined
❯ Fetching package.json from branch main
❯ Found pull request #9: 'chore(main): release 1.1.0'
⚠ There are untagged, merged release PRs outstanding - aborting
[]
```

As you can see, it failed to create the release-pr.  It also doesn't seem to respect the fact that PR 9 was closed unmerged.  That happens sometimes, where a PR gets closed unmerged.  

How are we supposed to handle these scenarios?  Is there a way to tell the system to ignore closed PR's and just prepare the release anyway?  If you need more information, please let me know, and thank you for any assistance you can provide.
