### ISSUE TITLE
Fine-grained Access Token Permissions ??

### ISSUE THREAD

**Issue by tippmar-nr** [googleapis/release-please#2146]
Our organization recently prohibited the use of "classic" personal access tokens and we're trying to get a fine-grained token properly configured for our Release Please workflow but have had nothing but frustration up to this point. 

I'm looking for either clarification that fine-grained tokens *cannot* be used with Release please or clear guidance on exactly which permissions the fine-grained token requires. 

Our latest attempt was to create a token owned by the organization, with access to all repos in the org and the following set of permissions: 
![image](https://github.com/googleapis/release-please/assets/120425148/f67cbcfc-607e-4848-84ec-7e5790a2a2b2)

Running the Release Please action fails with the following error: 
```
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "9effb5d[952](https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/7025799457/job/19147644084#step:4:953)984141af18634f7eb3073fc1bd44c3".
✖ Error when creating branch
✖ RequestError [HttpError]: Error creating Pull Request: Resource not accessible by personal access token
✔ Retry attempt #1...
    at /home/runner/work/_actions/google-github-actions/release-please-action/db8f2c60ee802b3748b512940dde88eabd7b7e01/dist/index.js:17035:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createBranch (/home/runner/work/_actions/google-github-actions/release-please-action/db8f2c60ee802b3748b512940dde88eabd7b7e01/dist/index.js:22494:26)
    at async branch (/home/runner/work/_actions/google-github-actions/release-please-action/db8f2c60ee802b3748b512940dde88eabd7b7e01/dist/index.js:22522:9)
    at async retry.retries (/home/runner/work/_actions/google-github-actions/release-please-action/db8f2c60ee802b3748b512940dde88eabd7b7e01/dist/index.js:23267:48)
    at async createPullRequest (/home/runner/work/_actions/google-github-actions/release-please-action/db8f2c60ee802b3748b512940dde88eabd7b7e01/dist/index.js:23267:24)
    at async /home/runner/work/_actions/google-github-actions/release-please-action/db8f2c60ee802b3748b512940dde88eabd7b7e01/dist/index.js:70286:30
    at async GitHub.createPullRequest (/home/runner/work/_actions/google-github-actions/release-please-action/db8f2c60ee802b3748b512940dde88eabd7b7e01/dist/index.js:71362:20)
    at async Manifest.createOrUpdatePullRequest (/home/runner/work/_actions/google-github-actions/release-please-action/db8f2c60ee802b3748b512940dde88eabd7b7e01/dist/index.js:71896:32) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/newrelic/newrelic-dotnet-agent/git/refs',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Wed, 29 Nov 2023 17:05:51 GMT',
      'github-authentication-token-expiration': '2024-02-27 11:02:26 -0600',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'contents=write; contents=write,workflows=write',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'B849:2496:12CCC18:2721F64:65676F6F',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4915',
      'x-ratelimit-reset': '1701279201',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '85',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by personal access token',
      documentation_url: 'https://docs.github.com/rest/git/refs#create-a-reference'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/newrelic/newrelic-dotnet-agent/git/refs',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.5 octokit-core.js/4.1.0 Node.js/16.20.2 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"ref":"refs/heads/release-please--branches--main","sha":"9effb5d952[984](https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/7025799457/job/19147644084#step:4:985)141af18634f7eb3073fc1bd44c3"}',
    request: { agent: undefined, hook: [Function: bound bound register] }
  }
}
```

Any guidance would be greatly appreciated!

**Comment by tippmar-nr** [comment]
Nevermind... Once the token referenced above was approved at the organization level, Release Please started working.
