### ISSUE TITLE
Specifying --config-file on the CLI breaks with "Missing required manifest config"

### ISSUE THREAD

**Issue by achingbrain** [googleapis/release-please#2149]
If I specify a config file on the CLI, internally the `argv.configFile` variable becomes an array containing both the default value and my override.

When the manifest releaser tries to download the original version it stringifies the array and fails:

```
ConfigurationError: base (libp2p/js-libp2p): Missing required manifest config: release-please-config.json,.release-please.json
    at fetchManifestConfig (/Users/alex/.nvm/versions/node/v20.8.0/lib/node_modules/release-please/build/src/manifest.js:859:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseConfig (/Users/alex/.nvm/versions/node/v20.8.0/lib/node_modules/release-please/build/src/manifest.js:812:20)
    at async Promise.all (index 0)
    at async Manifest.fromManifest (/Users/alex/.nvm/versions/node/v20.8.0/lib/node_modules/release-please/build/src/manifest.js:119:93)
    at async Object.handler (/Users/alex/.nvm/versions/node/v20.8.0/lib/node_modules/release-please/build/src/bin/release-please.js:380:24) {
  releaserName: 'base',
  repository: 'libp2p/js-libp2p'
}
```

If I manually patch the `createReleaseCommand` handler with something like `argv.configFile = argv.configFile.pop()` it works as expected.

Obviously not a solution, `yargs` should allow the value to be overridden, rather than changing the returned type of the argument.

#### Environment details

  - OS: Mac OS 13.5.1
  - Node.js version: 20.8.0
  - npm version: 10.1.0
  - `release-please` version: 16.3.1

#### Steps to reproduce

  1. `release-please github-release --config-file --repo-url libp2p/js-libp2p --config-file .release-please.json --debug --dry-run --token=$GITHUB_TOKEN`

**Comment by achingbrain** [comment]
Ah, no - this is user error, I had an empty `--config-file` in the CLI input.
