### ISSUE TITLE
[BUG] Error creating Pull Request: Not Found

### ISSUE THREAD

**Issue by Badisi** [googleapis/release-please#2260]
Bootstrapping **release-please** went fine.

But now that I actually have a commit that should trigger a `Release PR` the following error occurred:
```sh
✔ Starting GitHub PR workflow...
✖ Error when creating branch
✖ RequestError [HttpError]: Error creating Pull Request: Not Found
✔ Retry attempt #1...
    at /home/runner/work/_actions/google-github-actions/release-please-action/v4/dist/index.js:11190:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createBranch (/home/runner/work/_actions/google-github-actions/release-please-action/v4/dist/index.js:18125:26)
    at async branch (/home/runner/work/_actions/google-github-actions/release-please-action/v4/dist/index.js:18153:9)
    at async retry.retries (/home/runner/work/_actions/google-github-actions/release-please-action/v4/dist/index.js:18913:48)
    at async createPullRequest (/home/runner/work/_actions/google-github-actions/release-please-action/v4/dist/index.js:18913:24)
    at async /home/runner/work/_actions/google-github-actions/release-please-action/v4/dist/index.js:56858:30
    at async GitHub.createPullRequest (/home/runner/work/_actions/google-github-actions/release-please-action/v4/dist/index.js:57956:20)
    at async Manifest.createOrUpdatePullRequest (/home/runner/work/_actions/google-github-actions/release-please-action/v4/dist/index.js:58574:32)
    at async Promise.all (index 1) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/DSI-HUG/ngx-components/git/refs',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Fri, 05 Apr 2024 19:43:19 GMT',
      'github-authentication-token-expiration': '2024-05-26 11:33:35 UTC',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '4C02:689D:14F498:212BD8:66105456',
      'x-oauth-scopes': 'repo',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4899',
      'x-ratelimit-reset': '1712349537',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '101',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/git/refs#create-a-reference'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/DSI-HUG/ngx-components/git/refs',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.13 octokit-core.js/4.2.4 Node.js/20.8.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"ref":"refs/heads/release-please--branches--main--components--ngx-core","sha":"cc5aa709d0f679abd0067e0bf3fb6b807f458c3e"}',
    request: { agent: undefined, hook: [Function: bound bound register] }
  }
}
```

Complete run can be found [here](https://github.com/DSI-HUG/ngx-components/actions/runs/8574913940/job/23502761286#step:2:248)

I don't really understand what went wrong here because release-please should be creating the branch in this step.
So it is normal that it didn't finds it as it does not exists yet.

#### Environment details

  - OS: macos 12.6.8
  - Node.js version: v18.18.2
  - npm version: 10.5.1
  - `release-please` version: latest

**Comment by Badisi** [comment]
The error was actually misleading because the real issue was about permissions.
I was using a fine-grained token that had not enough permissions to create a new branch.

Would be good to update the documentation with actual required GitHub token's permissions though.

Closing
