### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by drstrangelooker** [googleapis/release-please#2414]
#### Environment details

  - OS: glinux (Debian)
  - Node.js version: v18.19.1
  - npm version: 7.24.1
  - `release-please` version: 16.14.3

#### Steps to reproduce

  1. `npm exec release-please release-pr -- --repo-url=looker-open-source/sdk-codegen --debug --dry-run --token=${GITHUB_TOKEN}`

Get
```
❯ ts-node was not bumped, ignoring
❯ typescript was not bumped, ignoring
❯ url-loader was not bumped, ignoring
❯ uuid was not bumped, ignoring
❯ webpack was not bumped, ignoring
❯ webpack-bundle-analyzer was not bumped, ignoring
❯ webpack-merge was not bumped, ignoring
✔ Post-processing 20 in-scope candidates
❯ running plugin: LinkedVersions
✔ found 7 linked-versions candidates
TypeError: Cannot read properties of undefined (reading 'replace')
    at safeBranchName ($HOME/release-please/node_modules/release-please/build/src/util/branch-name.js:214:23)
    at BranchName.ofGroupTargetBranch ($HOME/release-please/node_modules/release-please/build/src/util/branch-name.js:63:93)
    at LinkedVersions.run ($HOME/release-please/node_modules/release-please/build/src/plugins/linked-versions.js:128:58)
    at Manifest.buildPullRequests ($HOME/release-please/node_modules/release-please/build/src/manifest.js:405:51)
    at async Object.handler ($HOME/release-please/node_modules/release-please/build/src/bin/release-please.js:328:34)
```

**Comment by echoshihtw** [comment]
Hit this from a third trigger, which may help narrow the shared cause.

Mine was a migration rather than a fresh setup: the repo was already releasing fine as `my-app@0.1.0`, and I wanted bare `v1.0.0` tags instead. So neither `linked-versions` (this issue) nor `group-pull-request-title-pattern` (#2654) — just `"include-component-in-tag": false` with `"release-type": "node"`. Same stack:

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at safeBranchName (build/src/util/branch-name.js:214:23)
```

What I found while digging: `node` derives its component from `package.json`'s `name` and then uses that value *internally*, not only when rendering a tag. So `include-component-in-tag: false` doesn't hide the component — it empties it, and code paths downstream still assume one is present.

`python` and `simple` never derive a component at all, which is why an equivalent config works there: there's no value to empty in the first place. That reads as an architectural difference between the release types rather than a difference in defaults, and I couldn't find a flag on `node` that bridges it.

If that generalises, all three cases are the same shape: **the component is optional at the config surface but treated as guaranteed internally, so anything that empties it crashes rather than degrading.** An error raised at the point the component goes missing — rather than later, in `safeBranchName` — would have made this a five-minute problem instead of a day.

I gave up on bare tags and kept the component prefix:

```json
{
  "release-type": "node",
  "component": "my-app",
  "tag-separator": "@",
  "include-v-in-tag": false
}
```

which produces `my-app@0.1.0` without the `v`.

Longer writeup of the debugging path, if it's useful to anyone landing here from the error message: https://echoshih.com/blog/dont-fight-the-tools-defaults
