### ISSUE TITLE
bootstrap: TypeError: Cannot set properties of undefined (setting '.')

### ISSUE THREAD

**Issue by chickenandpork** [googleapis/release-please#2443]
When following the instructions for bootstrapping a config (which I'm doing to debug this appearance that release-please is ignoring the `release-please-config.json`), I'm experiencing a `TypeError: Cannot set properties of undefined (setting '.')` error rather than creating the initial config files.

The instructions for an OSX user who never, ever uses javascript, nor typescript, nor has nodes nor rpm installed, nor nvm, looks to be:

1. `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash`
2. `nvm install 22`
3. `nvm I release-please -g`
4. Create a GitHub CLASSIC token with repo write permissions; write it to a file
5. release-please bootstrap --token=$(cat file-with-gthub-token-written) --repo-url=<user>/<repo> --release-type=bazel

(I'm trying to use the "bazel" release-type, but not all documentation mentions it)

#### Environment details

  - OS: OSX-15.1.1 (intel)
  - Node.js version: 22.11.0
  - npm version:10.9.0
  - `release-please` version: 16.15.0

#### Steps to reproduce

  1. release-please bootstrap --token=$(cat file-with-github-token-written) --repo-url=<user>/<repo> --release-type=bazel
  2. stack dump follows
  
  (note: behaviour is the same with --repo-url of style "http://github.com/user/repo" or "user/repo") 

```
(node:5072) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
❯ Fetching .release-please-manifest.json from branch master
❯ Fetching release-please-config.json from branch master
release-please bootstrap

configure release manifest

... <dump of options> ...
TypeError: Cannot set properties of undefined (setting '.')
    at ReleasePleaseConfig.updateContent (/Users/allanc/.nvm/versions/node/v22.11.0/lib/node_modules/release-please/build/src/updaters/release-please-config.js:34:36)
    at GitHub.buildChangeSet (/Users/allanc/.nvm/versions/node/v22.11.0/lib/node_modules/release-please/build/src/github.js:1066:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /Users/allanc/.nvm/versions/node/v22.11.0/lib/node_modules/release-please/build/src/github.js:147:29
    at async GitHub.createPullRequest (/Users/allanc/.nvm/versions/node/v22.11.0/lib/node_modules/release-please/build/src/github.js:1247:20)
    at async Bootstrapper.bootstrap (/Users/allanc/.nvm/versions/node/v22.11.0/lib/node_modules/release-please/build/src/bootstrapper.js:31:16)
    at async Object.handler (/Users/allanc/.nvm/versions/node/v22.11.0/lib/node_modules/release-please/build/src/bin/release-please.js:534:33)
```

I'm not a Node user, nor NPM, so for all I know there's a user/piloting error.  There's a few steps forced as dependencies of other steps, and it's things I never do (like install npm) so the error might be in there.  Also, the install doesn't seem to lock down versions, so I might have a different yesterday's version of some dependency.

**Comment by chickenandpork** [comment]
Oh, that's funny: I went experimenting on this path again, ran into an error, googled to find a solution, and my bug was the first hit.  I'd forgotten I'd filed this :)

(still happening, and really, I'm a Node Idiot: just looking for a clue, or what a Node Expert would say "go, that's just..." when they see this)
