### ISSUE TITLE
bug(release-please): crashes with GraphqlError

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/release-please#946]
```
GraphqlError: Something went wrong while executing your query. Please include `5437:4DE9:517AF7:1824113:60A51EAD` when reporting this issue.
        at /workspace/node_modules/@octokit/graphql/dist-node/index.js:77:13
        at runMicrotasks (<anonymous>)
        at async GitHub.graphqlRequest (/workspace/node_modules/release-please/build/src/github.js:79:24)
        at async GitHub.mergeCommitsGraphQL (/workspace/node_modules/release-please/build/src/github.js:496:26)
        at async GitHub.mergeCommitIterator (/workspace/node_modules/release-please/build/src/github.js:603:30)
        at async JavaYoshi.latestTag (/workspace/node_modules/release-please/build/src/release-pr.js:403:26)
        at async JavaYoshi._run (/workspace/node_modules/release-please/build/src/releasers/java-yoshi.js:68:27)
        at async Function.Runner.runner (/workspace/build/src/runner.js:21:5)
        at async createReleasePR (/workspace/build/src/release-please.js:134:9) 
```

Starting as p2 cos' it's rare.

Other info:
compare: "https://github.com/googleapis/java-pubsublite/compare/f0feabb1cd65...13ff53bfe691"
modified: [
0: ".github/generated-files-bot.yml"
1: "synth.metadata"
]
```
message: "feat: add `gcf-owl-bot[bot]` to `ignoreAuthors` (#645)

This PR was generated using Autosynth. :rainbow:

Synth log will be available here:
https://source.cloud.google.com/results/invocations/64661f4d-5b51-4352-90ec-aee103f1388c/targets

- [ ] To automatically regenerate this PR, check this box. (May take up to 24 hours.)

Source-Link: https://github.com/googleapis/synthtool/commit/7332178a11ddddc91188dc0f25bca1ccadcaa6c6"
```

**Comment by chingor13** [comment]
There's not much actionable we can do here. We already attempt 3 times and we haven't seen this very often. If it occurs more often we can revisit.
